/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradersRouteImport } from './routes/traders'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ArcsRouteImport } from './routes/arcs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsIndexRouteImport } from './routes/items.index'
import { Route as UmamiScriptRouteImport } from './routes/umami/script'
import { Route as ItemsItemIdRouteImport } from './routes/items.$itemId'
import { Route as UmamiApiSplatRouteImport } from './routes/umami/api/$'

const TradersRoute = TradersRouteImport.update({
  id: '/traders',
  path: '/traders',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcsRoute = ArcsRouteImport.update({
  id: '/arcs',
  path: '/arcs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsRoute,
} as any)
const UmamiScriptRoute = UmamiScriptRouteImport.update({
  id: '/umami/script',
  path: '/umami/script',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => ItemsRoute,
} as any)
const UmamiApiSplatRoute = UmamiApiSplatRouteImport.update({
  id: '/umami/api/$',
  path: '/umami/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRoute
  '/events': typeof EventsRoute
  '/items': typeof ItemsRouteWithChildren
  '/quests': typeof QuestsRoute
  '/traders': typeof TradersRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/umami/script': typeof UmamiScriptRoute
  '/items/': typeof ItemsIndexRoute
  '/umami/api/$': typeof UmamiApiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRoute
  '/events': typeof EventsRoute
  '/quests': typeof QuestsRoute
  '/traders': typeof TradersRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/umami/script': typeof UmamiScriptRoute
  '/items': typeof ItemsIndexRoute
  '/umami/api/$': typeof UmamiApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcs': typeof ArcsRoute
  '/events': typeof EventsRoute
  '/items': typeof ItemsRouteWithChildren
  '/quests': typeof QuestsRoute
  '/traders': typeof TradersRoute
  '/items/$itemId': typeof ItemsItemIdRoute
  '/umami/script': typeof UmamiScriptRoute
  '/items/': typeof ItemsIndexRoute
  '/umami/api/$': typeof UmamiApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arcs'
    | '/events'
    | '/items'
    | '/quests'
    | '/traders'
    | '/items/$itemId'
    | '/umami/script'
    | '/items/'
    | '/umami/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arcs'
    | '/events'
    | '/quests'
    | '/traders'
    | '/items/$itemId'
    | '/umami/script'
    | '/items'
    | '/umami/api/$'
  id:
    | '__root__'
    | '/'
    | '/arcs'
    | '/events'
    | '/items'
    | '/quests'
    | '/traders'
    | '/items/$itemId'
    | '/umami/script'
    | '/items/'
    | '/umami/api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcsRoute: typeof ArcsRoute
  EventsRoute: typeof EventsRoute
  ItemsRoute: typeof ItemsRouteWithChildren
  QuestsRoute: typeof QuestsRoute
  TradersRoute: typeof TradersRoute
  UmamiScriptRoute: typeof UmamiScriptRoute
  UmamiApiSplatRoute: typeof UmamiApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traders': {
      id: '/traders'
      path: '/traders'
      fullPath: '/traders'
      preLoaderRoute: typeof TradersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcs': {
      id: '/arcs'
      path: '/arcs'
      fullPath: '/arcs'
      preLoaderRoute: typeof ArcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/umami/script': {
      id: '/umami/script'
      path: '/umami/script'
      fullPath: '/umami/script'
      preLoaderRoute: typeof UmamiScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/umami/api/$': {
      id: '/umami/api/$'
      path: '/umami/api/$'
      fullPath: '/umami/api/$'
      preLoaderRoute: typeof UmamiApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ItemsRouteChildren {
  ItemsItemIdRoute: typeof ItemsItemIdRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsItemIdRoute: ItemsItemIdRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcsRoute: ArcsRoute,
  EventsRoute: EventsRoute,
  ItemsRoute: ItemsRouteWithChildren,
  QuestsRoute: QuestsRoute,
  TradersRoute: TradersRoute,
  UmamiScriptRoute: UmamiScriptRoute,
  UmamiApiSplatRoute: UmamiApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
